const translations = {
    'af-ZA': {

        loading: "Besig om lirieke te laai",
        notFound: "Kon nie die lirieke vind nie.",
        writtenBy: "Geskryf deur: ",
        source: "Lirieke Verskaf Deur: ",
        notFoundError: "Dit lyk of ons nie die lirieke kan vertoon nie.",
        showTranslation: "Wys Vertaling",
        hideTranslation: "Versteek Vertaling",
        showPronunciation: "Wys Uitspraak",
        hidePronunciation: "Versteek Uitspraak",
        showOriginal: "Wys Oorspronklike",
        hideOriginal: "Versteek Oorspronklike",
        refreshLyrics: "Verfris lirieke",
        showTranslationOptions: "Wys vertaalopsies",
        offsetLyrics: "Liriek-verrekening",
        changeLyricsSource: "Verander liriekebron",
        reloadLyrics: "Herlaai lirieke",
        lyricsOptions: "Lirieke-opsies",
        back: "Terug",
        reset: "Herstel",
        autoSource: "Outomaties (Verstek)",
        sourceNotFound: "Geen lirieke vanaf hierdie bron gevind nie"
    },
    'az-AZ': {

        loading: "Mahnı sözləri yüklənir",
        notFound: "Mahnı sözləri tapılmadı.",
        writtenBy: "Müəllif: ",
        source: "Mahnı Sözləri Təmin Edildi: ",
        notFoundError: "Görünür, mahnı sözlərini göstərə bilmirik.",
        showTranslation: "Tərcüməni Göstər",
        hideTranslation: "Tərcüməni Gizlət",
        showPronunciation: "Tələffüzü Göstər",
        hidePronunciation: "Tələffüzü Gizlət",
        showOriginal: "Orijinalı Göstər",
        hideOriginal: "Orijinalı Gizlət",
        refreshLyrics: "Mahnı sözlərini yenilə",
        showTranslationOptions: "Tərcümə seçimlərini göstər",
        offsetLyrics: "Mahnı sözü ofseti",
        changeLyricsSource: "Mənbəni dəyişdir",
        reloadLyrics: "Sözləri yenidən yüklə",
        lyricsOptions: "Mahnı sözləri seçimləri",
        back: "Geri",
        reset: "Sıfırla",
        autoSource: "Avtomatik (Standart)",
        sourceNotFound: "Bu mənbədən mahnı sözləri tapılmadı"
    },
    'id-ID': {
        loading: "Memuat lirik",
        notFound: "Tidak dapat menemukan lirik.",
        writtenBy: "Ditulis oleh: ",
        source: "Lirik Disediakan Oleh: ",
        notFoundError: "Sepertinya kami tidak dapat menampilkan lirik.",
        showTranslation: "Tampilkan Terjemahan",
        hideTranslation: "Sembunyikan Terjemahan",
        showPronunciation: "Tampilkan Pengucapan",
        hidePronunciation: "Sembunyikan Pengucapan",
        showOriginal: "Tampilkan Asli",
        hideOriginal: "Sembunyikan Asli",
        refreshLyrics: "Muat ulang lirik",
        showTranslationOptions: "Tampilkan opsi terjemahan",
        offsetLyrics: "Offset Lirik",
        changeLyricsSource: "Ganti Sumber Lirik",
        reloadLyrics: "Muat Ulang Lirik",
        lyricsOptions: "Opsi Lirik",
        back: "Kembali",
        reset: "Reset",
        autoSource: "Otomatis (Bawaan)",
        sourceNotFound: "Lirik tidak ditemukan dari sumber ini"
    },
    'ms-MY': {

        loading: "Memuatkan lirik",
        notFound: "Tidak dapat mencari lirik.",
        writtenBy: "Ditulis oleh: ",
        source: "Lirik Disediakan Oleh: ",
        notFoundError: "Nampaknya kami tidak dapat memaparkan lirik.",
        showTranslation: "Tunjukkan Terjemahan",
        hideTranslation: "Sembunyikan Terjemahan",
        showPronunciation: "Tunjukkan Sebutan",
        hidePronunciation: "Sembunyikan Sebutan",
        showOriginal: "Tunjukkan Asal",
        hideOriginal: "Sembunyikan Asal",
        refreshLyrics: "Muat semula lirik",
        showTranslationOptions: "Tunjukkan pilihan terjemahan",
        offsetLyrics: "Ofset Lirik",
        changeLyricsSource: "Tukar Sumber Lirik",
        reloadLyrics: "Muat Semula Lirik",
        lyricsOptions: "Pilihan Lirik",
        back: "Kembali",
        reset: "Tetapkan Semula",
        autoSource: "Automatik (Lalai)",
        sourceNotFound: "Tiada lirik dijumpai daripada sumber ini"
    },
    'bs-BA': {

        loading: "Učitavanje teksta",
        notFound: "Nije moguće pronaći tekst.",
        writtenBy: "Napisao/la: ",
        source: "Tekst obezbijedio/la: ",
        notFoundError: "Čini se da ne možemo prikazati tekst.",
        showTranslation: "Prikaži prijevod",
        hideTranslation: "Sakrij prijevod",
        showPronunciation: "Prikaži izgovor",
        hidePronunciation: "Sakrij izgovor",
        showOriginal: "Prikaži Original",
        hideOriginal: "Sakrij Original",
        refreshLyrics: "Osvježi tekst",
        showTranslationOptions: "Prikaži opcije prijevoda",
        offsetLyrics: "Pomak teksta",
        changeLyricsSource: "Promijeni izvor teksta",
        reloadLyrics: "Ponovo učitaj tekst",
        lyricsOptions: "Opcije teksta",
        back: "Nazad",
        reset: "Poništi",
        autoSource: "Automatski (Zadano)",
        sourceNotFound: "Nisu pronađene riječi iz ovog izvora"
    },
    'ca-ES': {

        loading: "Carregant lletres",
        notFound: "No s'han pogut trobar les lletres.",
        writtenBy: "Escrit per: ",
        source: "Lletres proporcionades per: ",
        notFoundError: "Sembla que no podem mostrar les lletres.",
        showTranslation: "Mostra la traducció",
        hideTranslation: "Amaga la traducció",
        showPronunciation: "Mostra la pronunciació",
        hidePronunciation: "Amaga la pronunciació",
        showOriginal: "Mostra Original",
        hideOriginal: "Amaga Original",
        refreshLyrics: "Actualitza lletres",
        showTranslationOptions: "Mostra opcions de traducció",
        offsetLyrics: "Desplaçament de lletra",
        changeLyricsSource: "Canvia la font de lletra",
        reloadLyrics: "Recarrega la lletra",
        lyricsOptions: "Opcions de lletra",
        back: "Enrere",
        reset: "Restableix",
        autoSource: "Automàtic (Per defecte)",
        sourceNotFound: "No s'han trobat lletres d'aquesta font"
    },
    'cs-CZ': {

        loading: "Načítání textů",
        notFound: "Nepodařilo se najít texty.",
        writtenBy: "Napsal(a): ",
        source: "Texty poskytl(a): ",
        notFoundError: "Zdá se, že nemůžeme zobrazit texty.",
        showTranslation: "Zobrazit překlad",
        hideTranslation: "Skrýt překlad",
        showPronunciation: "Zobrazit výslovnost",
        hidePronunciation: "Skrýt výslovnost",
        showOriginal: "Zobrazit Originál",
        hideOriginal: "Skrýt Originál",
        refreshLyrics: "Obnovit texty",
        showTranslationOptions: "Zobrazit možnosti překladu",
        offsetLyrics: "Posun textu",
        changeLyricsSource: "Změnit zdroj textu",
        reloadLyrics: "Znovu načíst text",
        lyricsOptions: "Možnosti textu",
        back: "Zpět",
        reset: "Obnovit",
        autoSource: "Automaticky (Výchozí)",
        sourceNotFound: "Z tohoto zdroje nebyl nalezen žádný text"
    },
    'da-DK': {

        loading: "Indlæser sangtekster",
        notFound: "Kunne ikke finde sangteksterne.",
        writtenBy: "Skrevet af: ",
        source: "Sangtekster leveret af: ",
        notFoundError: "Det ser ud til, at vi ikke kan vise sangteksterne.",
        showTranslation: "Vis oversættelse",
        hideTranslation: "Skjul oversættelse",
        showPronunciation: "Vis udtale",
        hidePronunciation: "Skjul udtale",
        showOriginal: "Vis Original",
        hideOriginal: "Skjul Original",
        refreshLyrics: "Genindlæs sangtekster",
        showTranslationOptions: "Vis oversættelsesmuligheder",
        offsetLyrics: "Tekstforskydning",
        changeLyricsSource: "Skift tekstkilde",
        reloadLyrics: "Genindlæs tekst",
        lyricsOptions: "Tekstindstillinger",
        back: "Tilbage",
        reset: "Nulstil",
        autoSource: "Automatisk (Standard)",
        sourceNotFound: "Ingen sangtekst fundet fra denne kilde"
    },
    'de-DE': {

        loading: "Lade Liedtexte",
        notFound: "Konnte die Liedtexte nicht finden.",
        writtenBy: "Geschrieben von: ",
        source: "Liedtexte bereitgestellt von: ",
        notFoundError: "Es scheint, dass wir die Liedtexte nicht anzeigen können.",
        showTranslation: "Übersetzung anzeigen",
        hideTranslation: "Übersetzung ausblenden",
        showPronunciation: "Aussprache anzeigen",
        hidePronunciation: "Aussprache ausblenden",
        showOriginal: "Original anzeigen",
        hideOriginal: "Original ausblenden",
        refreshLyrics: "Liedtexte aktualisieren",
        showTranslationOptions: "Übersetzungsoptionen anzeigen",
        offsetLyrics: "Songtext-Versatz",
        changeLyricsSource: "Songtext-Quelle ändern",
        reloadLyrics: "Songtext neu laden",
        lyricsOptions: "Songtext-Optionen",
        back: "Zurück",
        reset: "Zurücksetzen",
        autoSource: "Automatisch (Standard)",
        sourceNotFound: "Kein Songtext von dieser Quelle gefunden"
    },
    'et-EE': {

        loading: "Laulude sõnade laadimine",
        notFound: "Laulusõnu ei leitud.",
        writtenBy: "Kirjutanud: ",
        source: "Laulusõnad pakub: ",
        notFoundError: "Tundub, et me ei saa laulusõnu kuvada.",
        showTranslation: "Kuva tõlge",
        hideTranslation: "Peida tõlge",
        showPronunciation: "Kuva hääldus",
        hidePronunciation: "Peida hääldus",
        showOriginal: "Kuva Originaal",
        hideOriginal: "Peida Originaal",
        refreshLyrics: "Värskenda laulusõnad",
        showTranslationOptions: "Kuva tõlkevalikud",
        offsetLyrics: "Sõnade nihe",
        changeLyricsSource: "Muuda sõnade allikat",
        reloadLyrics: "Laadi sõnad uuesti",
        lyricsOptions: "Sõnade valikud",
        back: "Tagasi",
        reset: "Lähtesta",
        autoSource: "Automaatne (Vaikimisi)",
        sourceNotFound: "Sellest allikast sõnu ei leitud"
    },
    'en-IN': {
        loading: "Loading lyrics",
        notFound: "Unable to find the lyrics.",
        writtenBy: "Written by: ",
        source: "Lyrics Provided By: ",
        notFoundError: "It seems we are unable to display the lyrics.",
        showTranslation: "Show Translation",
        hideTranslation: "Hide Translation",
        showPronunciation: "Show Pronunciation",
        hidePronunciation: "Hide Pronunciation",
        showOriginal: "Show Original",
        hideOriginal: "Hide Original",
        refreshLyrics: "Refresh Lyrics",
        showTranslationOptions: "Show Translation Options",
        offsetLyrics: "Lyrics Offset",
        changeLyricsSource: "Change Lyrics Source",
        reloadLyrics: "Reload Lyrics",
        lyricsOptions: "Lyrics Options",
        back: "Back",
        reset: "Reset",
        autoSource: "Automatic (Default)",
        sourceNotFound: "No lyrics found from this source"
    },
    'en-GB': {
        loading: "Loading lyrics",
        notFound: "Unable to find the lyrics.",
        writtenBy: "Written by: ",
        source: "Lyrics Provided By: ",
        notFoundError: "It seems we are unable to display the lyrics.",
        showTranslation: "Show Translation",
        hideTranslation: "Hide Translation",
        showPronunciation: "Show Pronunciation",
        hidePronunciation: "Hide Pronunciation",
        showOriginal: "Show Original",
        hideOriginal: "Hide Original",
        refreshLyrics: "Refresh Lyrics",
        showTranslationOptions: "Show Translation Options",
        offsetLyrics: "Lyrics Offset",
        changeLyricsSource: "Change Lyrics Source",
        reloadLyrics: "Reload Lyrics",
        lyricsOptions: "Lyrics Options",
        back: "Back",
        reset: "Reset",
        autoSource: "Automatic (Default)",
        sourceNotFound: "No lyrics found from this source"
    },
    'en-US': {
        loading: "Loading lyrics",
        notFound: "Unable to find the lyrics.",
        writtenBy: "Written by: ",
        source: "Lyrics Provided By: ",
        notFoundError: "It seems we are unable to display the lyrics.",
        showTranslation: "Show Translation",
        hideTranslation: "Hide Translation",
        showPronunciation: "Show Pronunciation",
        hidePronunciation: "Hide Pronunciation",
        showOriginal: "Show Original",
        hideOriginal: "Hide Original",
        refreshLyrics: "Refresh Lyrics",
        showTranslationOptions: "Show Translation Options",
        offsetLyrics: "Lyrics Offset",
        changeLyricsSource: "Change Lyrics Source",
        reloadLyrics: "Reload Lyrics",
        lyricsOptions: "Lyrics Options",
        back: "Back",
        reset: "Reset",
        autoSource: "Automatic (Default)",
        sourceNotFound: "No lyrics found from this source"
    },
    'es-ES': {

        loading: "Cargando letras",
        notFound: "No se pudo encontrar la letra.",
        writtenBy: "Escrito por: ",
        source: "Letras proporcionadas por: ",
        notFoundError: "Parece que no podemos mostrar la letra.",
        showTranslation: "Mostrar Traducción",
        hideTranslation: "Ocultar Traducción",
        showPronunciation: "Mostrar Pronunciación",
        hidePronunciation: "Ocultar Pronunciación",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Actualizar letras",
        showTranslationOptions: "Mostrar opciones de traducción",
        offsetLyrics: "Desfase de letra",
        changeLyricsSource: "Cambiar fuente de letra",
        reloadLyrics: "Recargar letra",
        lyricsOptions: "Opciones de letra",
        back: "Atrás",
        reset: "Restablecer",
        autoSource: "Automático (Predeterminado)",
        sourceNotFound: "No se encontraron letras de esta fuente"
    },
    'es-419': {

        loading: "Cargando letras",
        notFound: "No se pudo encontrar la letra.",
        writtenBy: "Escrito por: ",
        source: "Letras proporcionadas por: ",
        notFoundError: "Parece que no podemos mostrar la letra.",
        showTranslation: "Mostrar Traducción",
        hideTranslation: "Ocultar Traducción",
        showPronunciation: "Mostrar Pronunciación",
        hidePronunciation: "Ocultar Pronunciación",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Actualizar letras",
        showTranslationOptions: "Mostrar opciones de traducción",
        offsetLyrics: "Desfase de letra",
        changeLyricsSource: "Cambiar fuente de letra",
        reloadLyrics: "Recargar letra",
        lyricsOptions: "Opciones de letra",
        back: "Atrás",
        reset: "Restablecer",
        autoSource: "Automático (Predeterminado)",
        sourceNotFound: "No se encontraron letras de esta fuente"
    },
    'es-US': {

        loading: "Cargando letras",
        notFound: "No se pudo encontrar la letra.",
        writtenBy: "Escrito por: ",
        source: "Letras proporcionadas por: ",
        notFoundError: "Parece que no podemos mostrar la letra.",
        showTranslation: "Mostrar Traducción",
        hideTranslation: "Ocultar Traducción",
        showPronunciation: "Mostrar Pronunciación",
        hidePronunciation: "Ocultar Pronunciación",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Actualizar letras",
        showTranslationOptions: "Mostrar opciones de traducción",
        offsetLyrics: "Desfase de letra",
        changeLyricsSource: "Cambiar fuente de letra",
        reloadLyrics: "Recargar letra",
        lyricsOptions: "Opciones de letra",
        back: "Atrás",
        reset: "Restablecer",
        autoSource: "Automático (Predeterminado)",
        sourceNotFound: "No se encontraron letras de esta fuente"
    },
    'eu-ES': {

        loading: "Letrak kargatzen",
        notFound: "Ezin izan da letra aurkitu.",
        writtenBy: "Egilea: ",
        source: "Letrak hornituta: ",
        notFoundError: "Badirudi ezin ditugula letrak erakutsi.",
        showTranslation: "Erakutsi itzulpena",
        hideTranslation: "Ezkutatu itzulpena",
        showPronunciation: "Erakutsi ahoskera",
        hidePronunciation: "Ezkutatu ahoskera",
        showOriginal: "Erakutsi Originala",
        hideOriginal: "Ezkutatu Originala",
        refreshLyrics: "Letrak freskatu",
        showTranslationOptions: "Itzulpen aukerak erakutsi",
        offsetLyrics: "Letren desplazamendua",
        changeLyricsSource: "Aldatu letraren iturburua",
        reloadLyrics: "Kargatu berriro letrak",
        lyricsOptions: "Letren aukerak",
        back: "Atzera",
        reset: "Berrezarri",
        autoSource: "Automatikoa (Lehenetsia)",
        sourceNotFound: "Ez da letrarik aurkitu iturburu honetatik"
    },
    'fil-PH': {

        loading: "Nilo-load ang lyrics",
        notFound: "Hindi mahanap ang lyrics.",
        writtenBy: "Isinulat ni: ",
        source: "Lyrics Ibinigay Ni: ",
        notFoundError: "Mukhang hindi namin maipakita ang lyrics.",
        showTranslation: "Ipakita ang Pagsasalin",
        hideTranslation: "Itago ang Pagsasalin",
        showPronunciation: "Ipakita ang Pagbigkas",
        hidePronunciation: "Itago ang Pagbigkas",
        showOriginal: "Ipakita ang Orihinal",
        hideOriginal: "Itago ang Orihinal",
        refreshLyrics: "I-refresh ang lyrics",
        showTranslationOptions: "Ipakita ang mga opsyon sa pagsasalin",
        offsetLyrics: "Offset ng Lyrics",
        changeLyricsSource: "Palitan ang Source ng Lyrics",
        reloadLyrics: "I-reload ang Lyrics",
        lyricsOptions: "Mga Opsyon ng Lyrics",
        back: "Bumalik",
        reset: "I-reset",
        autoSource: "Awtomatiko (Default)",
        sourceNotFound: "Walang nahanap na lyrics mula sa source na ito"
    },
    'fr-FR': {

        loading: "Chargement des paroles",
        notFound: "Impossible de trouver les paroles.",
        writtenBy: "Écrit par: ",
        source: "Paroles fournies par : ",
        notFoundError: "Il semble que nous ne puissions pas afficher les paroles.",
        showTranslation: "Afficher la Traduction",
        hideTranslation: "Masquer la Traduction",
        showPronunciation: "Afficher la Prononciation",
        hidePronunciation: "Masquer la Prononciation",
        showOriginal: "Afficher l'Original",
        hideOriginal: "Masquer l'Original",
        refreshLyrics: "Actualiser les paroles",
        showTranslationOptions: "Afficher les options de traduction",
        offsetLyrics: "Décalage des paroles",
        changeLyricsSource: "Changer la source des paroles",
        reloadLyrics: "Recharger les paroles",
        lyricsOptions: "Options des paroles",
        back: "Retour",
        reset: "Réinitialiser",
        autoSource: "Automatique (Par défaut)",
        sourceNotFound: "Aucune parole trouvée depuis cette source"
    },
    'fr-CA': {

        loading: "Chargement des paroles",
        notFound: "Impossible de trouver les paroles.",
        writtenBy: "Écrit par: ",
        source: "Paroles fournies par : ",
        notFoundError: "Il semble que nous ne puissions pas afficher les paroles.",
        showTranslation: "Afficher la traduction",
        hideTranslation: "Masquer la traduction",
        showPronunciation: "Afficher la prononciation",
        hidePronunciation: "Masquer la prononciation",
        showOriginal: "Afficher l'Original",
        hideOriginal: "Masquer l'Original",
        refreshLyrics: "Actualiser les paroles",
        showTranslationOptions: "Afficher les options de traduction",
        offsetLyrics: "Décalage des paroles",
        changeLyricsSource: "Changer la source des paroles",
        reloadLyrics: "Recharger les paroles",
        lyricsOptions: "Options des paroles",
        back: "Retour",
        reset: "Réinitialiser",
        autoSource: "Automatique (Par défaut)",
        sourceNotFound: "Aucune parole trouvée depuis cette source"
    },
    'gl-ES': {

        loading: "Cargando letras",
        notFound: "Non se puideron atopar as letras.",
        writtenBy: "Escrito por: ",
        source: "Letras proporcionadas por: ",
        notFoundError: "Parece que non podemos mostrar as letras.",
        showTranslation: "Mostrar tradución",
        hideTranslation: "Ocultar tradución",
        showPronunciation: "Mostrar pronunciación",
        hidePronunciation: "Ocultar pronunciación",
        showOriginal: "Mostrar Orixinal",
        hideOriginal: "Ocultar Orixinal",
        refreshLyrics: "Actualizar letras",
        showTranslationOptions: "Mostrar opcións de tradución",
        offsetLyrics: "Desprazamento da letra",
        changeLyricsSource: "Cambiar fonte da letra",
        reloadLyrics: "Recargar letra",
        lyricsOptions: "Opcións de letra",
        back: "Atrás",
        reset: "Restablecer",
        autoSource: "Automático (Predeterminado)",
        sourceNotFound: "Non se atoparon letras desta fonte"
    },
    'hr-HR': {

        loading: "Učitavanje stihova",
        notFound: "Nije moguće pronaći stihove.",
        writtenBy: "Napisao/la: ",
        source: "Stihove osigurao/la: ",
        notFoundError: "Čini se da ne možemo prikazati stihove.",
        showTranslation: "Prikaži prijevod",
        hideTranslation: "Sakrij prijevod",
        showPronunciation: "Prikaži izgovor",
        hidePronunciation: "Sakrij izgovor",
        showOriginal: "Prikaži Original",
        hideOriginal: "Sakrij Original",
        refreshLyrics: "Osvježi stihove",
        showTranslationOptions: "Prikaži opcije prijevoda",
        offsetLyrics: "Pomak teksta",
        changeLyricsSource: "Promijeni izvor teksta",
        reloadLyrics: "Ponovno učitaj tekst",
        lyricsOptions: "Opcije teksta",
        back: "Natrag",
        reset: "Poništi",
        autoSource: "Automatski (Zadano)",
        sourceNotFound: "Nisu pronađene riječi iz ovog izvora"
    },
    'zu-ZA': {

        loading: "Iyalayisha amagama",
        notFound: "Ayikwazanga ukuthola amagama.",
        writtenBy: "Ibhalwe ngu: ",
        source: "Amagama anikezwe ngu: ",
        notFoundError: "Kubukeka sengathi asikwazi ukubonisa amagama.",
        showTranslation: "Bonisa Ukuhumusha",
        hideTranslation: "Fihla Ukuhumusha",
        showPronunciation: "Bonisa Ukuphimisela",
        hidePronunciation: "Fihla Ukuphimisela",
        showOriginal: "Bonisa Okwangempela",
        hideOriginal: "Fihla Okwangempela",
        refreshLyrics: "Vuselela Amagama",
        showTranslationOptions: "Bonisa Izinketho Zokuhumusha",
        offsetLyrics: "Ukucheza kwamazwi",
        changeLyricsSource: "Shintsha umthombo wamazwi",
        reloadLyrics: "Layisha kabusha amazwi",
        lyricsOptions: "Izinketho zamazwi",
        back: "Emuva",
        reset: "Setha kabusha",
        autoSource: "Ngokuzenzakalelayo (Okuzenzakalelayo)",
        sourceNotFound: "Awekho amazwi atholakele kulo mthombo"
    },
    'is-IS': {

        loading: "Hleð textum",
        notFound: "Gat ekki fundið textana.",
        writtenBy: "Höfundur: ",
        source: "Textar veittir af: ",
        notFoundError: "Svo virðist sem við getum ekki birt textana.",
        showTranslation: "Sýna þýðingu",
        hideTranslation: "Fela þýðingu",
        showPronunciation: "Sýna framburð",
        hidePronunciation: "Fela framburð",
        showOriginal: "Sýna Frumrit",
        hideOriginal: "Fela Frumrit",
        refreshLyrics: "Endurhlaða texta",
        showTranslationOptions: "Sýna þýðingarvalkosti",
        offsetLyrics: "Textahliðrun",
        changeLyricsSource: "Breyta textauppsprettu",
        reloadLyrics: "Endurhlaða texta",
        lyricsOptions: "Textavalkostir",
        back: "Til baka",
        reset: "Endurstilla",
        autoSource: "Sjálfvirkt (Sjálfgefið)",
        sourceNotFound: "Enginn texti fannst úr þessari uppsprettu"
    },
    'it-IT': {

        loading: "Caricamento dei testi",
        notFound: "Impossibile trovare i testi.",
        writtenBy: "Scritto da: ",
        source: "Testi forniti da: ",
        notFoundError: "Sembra che non possiamo mostrare i testi.",
        showTranslation: "Mostra Traduzione",
        hideTranslation: "Nascondi Traduzione",
        showPronunciation: "Mostra Pronuncia",
        hidePronunciation: "Nascondi Pronuncia",
        showOriginal: "Mostra Originale",
        hideOriginal: "Nascondi Originale",
        refreshLyrics: "Aggiorna testi",
        showTranslationOptions: "Mostra opzioni di traduzione",
        offsetLyrics: "Offset del testo",
        changeLyricsSource: "Cambia sorgente del testo",
        reloadLyrics: "Ricarica testo",
        lyricsOptions: "Opzioni testo",
        back: "Indietro",
        reset: "Reimposta",
        autoSource: "Automatico (Predefinito)",
        sourceNotFound: "Nessun testo trovato da questa sorgente"
    },
    'sw-KE': {

        loading: "Inapakia maneno ya wimbo",
        notFound: "Imeshindwa kupata maneno ya wimbo.",
        writtenBy: "Imeandikwa na: ",
        source: "Maneno ya wimbo yametolewa na: ",
        notFoundError: "Inaonekana hatuwezi kuonyesha maneno ya wimbo.",
        showTranslation: "Onyesha Tafsiri",
        hideTranslation: "Ficha Tafsiri",
        showPronunciation: "Onyesha Matamshi",
        hidePronunciation: "Ficha Matamshi",
        showOriginal: "Onyesha Asili",
        hideOriginal: "Ficha Asili",
        refreshLyrics: "Onyesha upya maneno ya wimbo",
        showTranslationOptions: "Onyesha chaguo za tafsiri",
        offsetLyrics: "Mkengeuko wa maneno",
        changeLyricsSource: "Badilisha chanzo cha maneno",
        reloadLyrics: "Pakia upya maneno",
        lyricsOptions: "Chaguo za maneno",
        back: "Nyuma",
        reset: "Weka upya",
        autoSource: "Otomatiki (Chaguomsingi)",
        sourceNotFound: "Hakuna maneno yaliyopatikana kutoka chanzo hiki"
    },
    'lv-LV': {

        loading: "Notiek dziesmu vārdu ielāde",
        notFound: "Nevarēja atrast dziesmas vārdus.",
        writtenBy: "Autors: ",
        source: "Dziesmu vārdus nodrošina: ",
        notFoundError: "Šķiet, ka mēs nevaram parādīt dziesmas vārdus.",
        showTranslation: "Rādīt tulkojumu",
        hideTranslation: "Slēpt tulkojumu",
        showPronunciation: "Rādīt izrunu",
        hidePronunciation: "Slēpt izrunu",
        showOriginal: "Rādīt Oriģinālu",
        hideOriginal: "Slēpt Oriģinālu",
        refreshLyrics: "Atsvaidzināt dziesmu vārdus",
        showTranslationOptions: "Rādīt tulkošanas iespējas",
        offsetLyrics: "Vārdu nobīde",
        changeLyricsSource: "Mainīt vārdu avotu",
        reloadLyrics: "Pārlādēt vārdus",
        lyricsOptions: "Vārdu opcijas",
        back: "Atpakaļ",
        reset: "Atiestatīt",
        autoSource: "Automātiski (Noklusējums)",
        sourceNotFound: "Šajā avotā dziesmas vārdi netika atrasti"
    },
    'lt-LT': {

        loading: "Įkeliami dainų žodžiai",
        notFound: "Nepavyko rasti dainų žodžių.",
        writtenBy: "Parašė: ",
        source: "Dainų žodžius pateikė: ",
        notFoundError: "Atrodo, kad negalime parodyti dainų žodžių.",
        showTranslation: "Rodyti vertimą",
        hideTranslation: "Slėpti vertimą",
        showPronunciation: "Rodyti tarimą",
        hidePronunciation: "Slėpti tarimą",
        showOriginal: "Rodyti Originalą",
        hideOriginal: "Slėpti Originalą",
        refreshLyrics: "Atnaujinti dainų žodžius",
        showTranslationOptions: "Rodyti vertimo parinktis",
        offsetLyrics: "Žodžių poslinkis",
        changeLyricsSource: "Keisti žodžių šaltinį",
        reloadLyrics: "Iš naujo įkelti žodžius",
        lyricsOptions: "Žodžių parinktys",
        back: "Atgal",
        reset: "Atkurti",
        autoSource: "Automatinis (Numatytasis)",
        sourceNotFound: "Šiame šaltinyje dainos žodžių nerasta"
    },
    'hu-HU': {

        loading: "Dalszövegek betöltése",
        notFound: "Nem található a dalszöveg.",
        writtenBy: "Írta: ",
        source: "Dalszöveget biztosította: ",
        notFoundError: "Úgy tűnik, nem tudjuk megjeleníteni a dalszöveget.",
        showTranslation: "Fordítás megjelenítése",
        hideTranslation: "Fordítás elrejtése",
        showPronunciation: "Kiejtés megjelenítése",
        hidePronunciation: "Kiejtés elrejtése",
        showOriginal: "Eredeti Megjelenítése",
        hideOriginal: "Eredeti Elrejtése",
        refreshLyrics: "Dalszövegek frissítése",
        showTranslationOptions: "Fordítási lehetőségek megjelenítése",
        offsetLyrics: "Dalszöveg eltolás",
        changeLyricsSource: "Dalszöveg forrásának módosítása",
        reloadLyrics: "Dalszöveg újratöltése",
        lyricsOptions: "Dalszöveg beállításai",
        back: "Vissza",
        reset: "Visszaállítás",
        autoSource: "Automatikus (Alapértelmezett)",
        sourceNotFound: "Nem található dalszöveg ebből a forrásból"
    },
    'nl-NL': {

        loading: "Songtekst laden",
        notFound: "Songtekst niet gevonden.",
        writtenBy: "Geschreven door: ",
        source: "Songtekst geleverd door: ",
        notFoundError: "Het lijkt erop dat we de songtekst niet kunnen weergeven.",
        showTranslation: "Vertaling weergeven",
        hideTranslation: "Vertaling verbergen",
        showPronunciation: "Uitspraak weergeven",
        hidePronunciation: "Uitspraak verbergen",
        showOriginal: "Origineel Weergeven",
        hideOriginal: "Origineel Verbergen",
        refreshLyrics: "Songtekst vernieuwen",
        showTranslationOptions: "Vertalingsopties weergeven",
        offsetLyrics: "Songtekst-vertraging",
        changeLyricsSource: "Songtekstbron wijzigen",
        reloadLyrics: "Songtekst opnieuw laden",
        lyricsOptions: "Songtekstopties",
        back: "Terug",
        reset: "Herstellen",
        autoSource: "Automatisch (Standaard)",
        sourceNotFound: "Geen songtekst gevonden van deze bron"
    },
    'no-NO': {

        loading: "Laster inn sangtekster",
        notFound: "Fant ikke sangtekstene.",
        writtenBy: "Skrevet av: ",
        source: "Sangtekster levert av: ",
        notFoundError: "Det ser ut til at vi ikke kan vise sangtekstene.",
        showTranslation: "Vis oversettelse",
        hideTranslation: "Skjul oversettelse",
        showPronunciation: "Vis uttale",
        hidePronunciation: "Skjul uttale",
        showOriginal: "Vis Original",
        hideOriginal: "Skjul Original",
        refreshLyrics: "Last inn sangtekster på nytt",
        showTranslationOptions: "Vis oversettelsesalternativer",
        offsetLyrics: "Tekstforskyvning",
        changeLyricsSource: "Endre tekstkilde",
        reloadLyrics: "Last inn tekst på nytt",
        lyricsOptions: "Tekstalternativer",
        back: "Tilbake",
        reset: "Tilbakestill",
        autoSource: "Automatisk (Standard)",
        sourceNotFound: "Ingen sangtekst funnet fra denne kilden"
    },
    'uz-UZ': {

        loading: "Qo'shiq matnlari yuklanmoqda",
        notFound: "Qo'shiq matnlari topilmadi.",
        writtenBy: "Muallif: ",
        source: "Qo'shiq matnlari taqdim etilgan: ",
        notFoundError: "Ko'rinishidan, biz qo'shiq matnlarini ko'rsata olmaymiz.",
        showTranslation: "Tarjimani ko'rsatish",
        hideTranslation: "Tarjimani yashirish",
        showPronunciation: "Talaffuzni ko'rsatish",
        hidePronunciation: "Talaffuzni yashirish",
        showOriginal: "Aslini Ko'rsatish",
        hideOriginal: "Aslini Yashirish",
        refreshLyrics: "Qo'shiq matnlarini yangilash",
        showTranslationOptions: "Tarjima variantlarini ko'rsatish",
        offsetLyrics: "Matn siljishi",
        changeLyricsSource: "Matn manbasini o'zgartirish",
        reloadLyrics: "Matnni qayta yuklash",
        lyricsOptions: "Matn parametrlari",
        back: "Orqaga",
        reset: "Qayta sozlash",
        autoSource: "Avtomatik (Birlamchi)",
        sourceNotFound: "Ushbu manbadan matn topilmadi"
    },
    'pl-PL': {

        loading: "Ładowanie tekstu piosenki",
        notFound: "Nie można znaleźć tekstu piosenki.",
        writtenBy: "Napisane przez: ",
        source: "Tekst piosenki dostarczony przez: ",
        notFoundError: "Wygląda na to, że nie możemy wyświetlić tekstu piosenki.",
        showTranslation: "Pokaż tłumaczenie",
        hideTranslation: "Ukryj tłumaczenie",
        showPronunciation: "Pokaż wymowę",
        hidePronunciation: "Ukryj wymowę",
        showOriginal: "Pokaż Oryginał",
        hideOriginal: "Ukryj Oryginał",
        refreshLyrics: "Odśwież tekst piosenki",
        showTranslationOptions: "Pokaż opcje tłumaczenia",
        offsetLyrics: "Przesunięcie tekstu",
        changeLyricsSource: "Zmień źródło tekstu",
        reloadLyrics: "Przeładuj tekst",
        lyricsOptions: "Opcje tekstu",
        back: "Wstecz",
        reset: "Resetuj",
        autoSource: "Automatycznie (Domyślnie)",
        sourceNotFound: "Nie znaleziono tekstu z tego źródła"
    },
    'pt-PT': {

        loading: "A carregar letras",
        notFound: "Não foi possível encontrar as letras.",
        writtenBy: "Escrito por: ",
        source: "Letras fornecidas por: ",
        notFoundError: "Parece que não conseguimos apresentar as letras.",
        showTranslation: "Mostrar Tradução",
        hideTranslation: "Ocultar Tradução",
        showPronunciation: "Mostrar Pronúncia",
        hidePronunciation: "Ocultar Pronúncia",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Atualizar Letras",
        showTranslationOptions: "Mostrar Opções de Tradução",
        offsetLyrics: "Deslocamento da letra",
        changeLyricsSource: "Alterar fonte da letra",
        reloadLyrics: "Recarregar letra",
        lyricsOptions: "Opções de letra",
        back: "Voltar",
        reset: "Repor",
        autoSource: "Automático (Predefinição)",
        sourceNotFound: "Nenhuma letra encontrada a partir desta fonte"
    },
    'pt-BR': {

        loading: "Carregando letras",
        notFound: "Não foi possível encontrar a letra.",
        writtenBy: "Escrito por: ",
        source: "Letras fornecidas por: ",
        notFoundError: "Parece que não conseguimos exibir a letra.",
        showTranslation: "Mostrar Tradução",
        hideTranslation: "Ocultar Tradução",
        showPronunciation: "Mostrar Pronúncia",
        hidePronunciation: "Ocultar Pronúncia",
        showOriginal: "Mostrar Original",
        hideOriginal: "Ocultar Original",
        refreshLyrics: "Atualizar Letras",
        showTranslationOptions: "Mostrar Opções de Tradução",
        offsetLyrics: "Deslocamento da letra",
        changeLyricsSource: "Alterar fonte da letra",
        reloadLyrics: "Recarregar letra",
        lyricsOptions: "Opções de letra",
        back: "Voltar",
        reset: "Redefinir",
        autoSource: "Automático (Padrão)",
        sourceNotFound: "Nenhuma letra encontrada a partir desta fonte"
    },
    'ro-RO': {

        loading: "Se încarcă versurile",
        notFound: "Nu s-au găsit versurile.",
        writtenBy: "Scris de: ",
        source: "Versuri furnizate de: ",
        notFoundError: "Se pare că nu putem afișa versurile.",
        showTranslation: "Afișează traducerea",
        hideTranslation: "Ascunde traducerea",
        showPronunciation: "Afișează pronunția",
        hidePronunciation: "Ascunde pronunția",
        showOriginal: "Afișează Originalul",
        hideOriginal: "Ascunde Originalul",
        refreshLyrics: "Reîmprospătează versurile",
        showTranslationOptions: "Afișează opțiunile de traducere",
        offsetLyrics: "Decalaj versuri",
        changeLyricsSource: "Schimbă sursa versurilor",
        reloadLyrics: "Reîncarcă versurile",
        lyricsOptions: "Opțiuni versuri",
        back: "Înapoi",
        reset: "Resetează",
        autoSource: "Automat (Implicit)",
        sourceNotFound: "Nu s-au găsit versuri din această sursă"
    },
    'sq-AL': {

        loading: "Po ngarkohen tekstet",
        notFound: "Nuk u gjetën tekstet.",
        writtenBy: "Shkruar nga: ",
        source: "Tekstet ofrohen nga: ",
        notFoundError: "Duket se nuk mund t'i shfaqim tekstet.",
        showTranslation: "Shfaq Përkthimin",
        hideTranslation: "Fshih Përkthimin",
        showPronunciation: "Shfaq Bigkasimin",
        hidePronunciation: "Fshih Bigkasimin",
        showOriginal: "Shfaq Origjinalin",
        hideOriginal: "Fshih Origjinalin",
        refreshLyrics: "Rifresko tekstet",
        showTranslationOptions: "Shfaq opsionet e përkthimit",
        offsetLyrics: "Zhbendja e tekstit",
        changeLyricsSource: "Ndrysho burimin e tekstit",
        reloadLyrics: "Ringarko tekstin",
        lyricsOptions: "Opsionet e tekstit",
        back: "Prapa",
        reset: "Rivendos",
        autoSource: "Automatik (Parazgjedhur)",
        sourceNotFound: "Nuk u gjet asnjë tekst nga ky burim"
    },
    'sk-SK': {

        loading: "Načítavajú sa texty",
        notFound: "Nepodarilo sa nájsť texty.",
        writtenBy: "Autor: ",
        source: "Texty poskytol: ",
        notFoundError: "Zdá sa, že nemôžeme zobraziť texty.",
        showTranslation: "Zobraziť preklad",
        hideTranslation: "Skryť preklad",
        showPronunciation: "Zobraziť výslovnosť",
        hidePronunciation: "Skryť výslovnosť",
        showOriginal: "Zobraziť Originál",
        hideOriginal: "Skryť Originál",
        refreshLyrics: "Obnoviť texty",
        showTranslationOptions: "Zobraziť možnosti prekladu",
        offsetLyrics: "Posun textu",
        changeLyricsSource: "Zmeniť zdroj textu",
        reloadLyrics: "Znova načítať text",
        lyricsOptions: "Možnosti textu",
        back: "Späť",
        reset: "Obnoviť",
        autoSource: "Automaticky (Predvolené)",
        sourceNotFound: "Z tohto zdroja sa nenašiel žiadny text"
    },
    'sl-SI': {

        loading: "Nalaganje besedil",
        notFound: "Ni mogoče najti besedil.",
        writtenBy: "Avtor: ",
        source: "Besedila zagotovil: ",
        notFoundError: "Kaže, da besedil ne moremo prikazati.",
        showTranslation: "Prikaži prevod",
        hideTranslation: "Skrij prevod",
        showPronunciation: "Prikaži izgovorjavo",
        hidePronunciation: "Skrij izgovorjavo",
        showOriginal: "Prikaži Izvirnik",
        hideOriginal: "Skrij Izvirnik",
        refreshLyrics: "Osveži besedila",
        showTranslationOptions: "Prikaži možnosti prevajanja",
        offsetLyrics: "Zamik besedila",
        changeLyricsSource: "Spremeni vir besedila",
        reloadLyrics: "Znova naloži besedilo",
        lyricsOptions: "Možnosti besedila",
        back: "Nazaj",
        reset: "Ponastavi",
        autoSource: "Samodejno (Privzeto)",
        sourceNotFound: "Iz tega vira ni bilo najdeno besedilo"
    },
    'sr-Latn': {
        loading: "Učitavanje teksta",
        notFound: "Nije moguće pronaći tekst.",
        writtenBy: "Napisao/la: ",
        source: "Tekst obezbedio/la: ",
        notFoundError: "Čini se da ne možemo da prikažemo tekst.",
        showTranslation: "Prikaži prevod",
        hideTranslation: "Sakrij prevod",
        showPronunciation: "Prikaži izgovor",
        hidePronunciation: "Sakrij izgovor",
        showOriginal: "Prikaži Original",
        hideOriginal: "Sakrij Original",
        refreshLyrics: "Osveži tekst",
        showTranslationOptions: "Prikaži opcije prevoda"
    },
    'fi-FI': {

        loading: "Ladataan sanoituksia",
        notFound: "Sanoituksia ei löytynyt.",
        writtenBy: "Kirjoittanut: ",
        source: "Sanoitukset toimittanut: ",
        notFoundError: "Näyttää siltä, että emme voi näyttää sanoituksia.",
        showTranslation: "Näytä käännös",
        hideTranslation: "Piilota käännös",
        showPronunciation: "Näytä ääntäminen",
        hidePronunciation: "Piilota ääntäminen",
        showOriginal: "Näytä Alkuperäinen",
        hideOriginal: "Piilota Alkuperäinen",
        refreshLyrics: "Päivitä sanoitukset",
        showTranslationOptions: "Näytä käännösvaihtoehdot",
        offsetLyrics: "Sanoitusten viive",
        changeLyricsSource: "Vaihda sanoitusten lähdettä",
        reloadLyrics: "Lataa sanoitukset uudelleen",
        lyricsOptions: "Sanoitusasetukset",
        back: "Takaisin",
        reset: "Palauta",
        autoSource: "Automaattinen (Oletus)",
        sourceNotFound: "Tästä lähteestä ei löytynyt sanoituksia"
    },
    'sv-SE': {

        loading: "Laddar låttexter",
        notFound: "Kunde inte hitta låttexten.",
        writtenBy: "Skriven av: ",
        source: "Låttexter tillhandahållna av: ",
        notFoundError: "Det verkar som att vi inte kan visa låttexten.",
        showTranslation: "Visa översättning",
        hideTranslation: "Dölj översättning",
        showPronunciation: "Visa uttal",
        hidePronunciation: "Dölj uttal",
        showOriginal: "Visa Original",
        hideOriginal: "Dölj Original",
        refreshLyrics: "Uppdatera låttexter",
        showTranslationOptions: "Visa översättningsalternativ",
        offsetLyrics: "Textförskjutning",
        changeLyricsSource: "Byt textkälla",
        reloadLyrics: "Ladda om text",
        lyricsOptions: "Textalternativ",
        back: "Tillbaka",
        reset: "Återställ",
        autoSource: "Automatiskt (Standard)",
        sourceNotFound: "Ingen text hittades från denna källa"
    },
    'vi-VN': {

        loading: "Đang tải lời bài hát",
        notFound: "Không tìm thấy lời bài hát.",
        writtenBy: "Sáng tác: ",
        source: "Lời bài hát được cung cấp bởi: ",
        notFoundError: "Có vẻ như chúng tôi không thể hiển thị lời bài hát.",
        showTranslation: "Hiển thị bản dịch",
        hideTranslation: "Ẩn bản dịch",
        showPronunciation: "Hiển thị cách phát âm",
        hidePronunciation: "Ẩn cách phát âm",
        showOriginal: "Hiển thị Bản gốc",
        hideOriginal: "Ẩn Bản gốc",
        refreshLyrics: "Làm mới lời bài hát",
        showTranslationOptions: "Hiển thị tùy chọn dịch",
        offsetLyrics: "Độ trễ lời bài hát",
        changeLyricsSource: "Đổi nguồn lời bài hát",
        reloadLyrics: "Tải lại lời bài hát",
        lyricsOptions: "Tùy chọn lời bài hát",
        back: "Quay lại",
        reset: "Đặt lại",
        autoSource: "Tự động (Mặc định)",
        sourceNotFound: "Không tìm thấy lời bài hát từ nguồn này"
    },
    'tr-TR': {

        loading: "Şarkı sözleri yükleniyor",
        notFound: "Şarkı sözleri bulunamadı.",
        writtenBy: "Yazan: ",
        source: "Şarkı Sözleri Sağlayıcısı: ",
        notFoundError: "Görünüşe göre şarkı sözlerini görüntüleyemiyoruz.",
        showTranslation: "Çeviriyi Göster",
        hideTranslation: "Çeviriyi Gizle",
        showPronunciation: "Telaffuzu Göster",
        hidePronunciation: "Telaffuzu Gizle",
        showOriginal: "Orijinali Göster",
        hideOriginal: "Orijinali Gizle",
        refreshLyrics: "Şarkı Sözlerini Yenile",
        showTranslationOptions: "Çeviri Seçeneklerini Göster",
        offsetLyrics: "Şarkı Sözü Zamanlaması",
        changeLyricsSource: "Şarkı Sözü Kaynağını Değiştir",
        reloadLyrics: "Sözleri Yeniden Yükle",
        lyricsOptions: "Şarkı Sözü Seçenekleri",
        back: "Geri",
        reset: "Sıfırla",
        autoSource: "Otomatik (Varsayılan)",
        sourceNotFound: "Bu kaynaktan şarkı sözü bulunamadı"
    },
    'be-BY': {

        loading: "Загрузка тэкстаў",
        notFound: "Немагчыма знайсці тэксты.",
        writtenBy: "Аўтар: ",
        source: "Тэксты прадастаўлены: ",
        notFoundError: "Здаецца, мы не можам адлюstraваць тэксты.",
        showTranslation: "Паказаць пераклад",
        hideTranslation: "Схаваць пераклад",
        showPronunciation: "Паказаць вымаўленне",
        hidePronunciation: "Схаваць вымаўленне",
        showOriginal: "Паказаць Арыгінал",
        hideOriginal: "Схаваць Арыгінал",
        refreshLyrics: "Абнавіць тэксты",
        showTranslationOptions: "Паказаць параметры перакладу",
        offsetLyrics: "Зрух тэксту",
        changeLyricsSource: "Змяніць крыніцу тэксту",
        reloadLyrics: "Перазагрузіць тэкст",
        lyricsOptions: "Параметры тэксту",
        back: "Назад",
        reset: "Скінуць",
        autoSource: "Аўтаматычна (Па змаўчанні)",
        sourceNotFound: "Тэкст з гэтай крыніцы не знойдзены"
    },
    'bg-BG': {

        loading: "Зареждане на текстове",
        notFound: "Не могат да бъдат намерени текстовете.",
        writtenBy: "Написано от: ",
        source: "Текстове, предоставени от: ",
        notFoundError: "Изглежда, че не можем да покажем текстовете.",
        showTranslation: "Показване на превода",
        hideTranslation: "Скриване на превода",
        showPronunciation: "Показване на произношението",
        hidePronunciation: "Скриване на произношението",
        showOriginal: "Показване на Оригинала",
        hideOriginal: "Скриване на Оригинала",
        refreshLyrics: "Опресняване на текстове",
        showTranslationOptions: "Показване на опции за превод",
        offsetLyrics: "Изместване на текста",
        changeLyricsSource: "Смяна на източника на текст",
        reloadLyrics: "Презареждане на текста",
        lyricsOptions: "Опции за текста",
        back: "Назад",
        reset: "Нулиране",
        autoSource: "Автоматично (По подразбиране)",
        sourceNotFound: "Не е намерен текст от този източник"
    },
    'ky-KG': {

        loading: "Ырдын текстин жүктөө",
        notFound: "Ырдын тексти табылган жок.",
        writtenBy: "Автору: ",
        source: "Ырдын тексти берилди: ",
        notFoundError: "Кыязы, биз ырдын текстин көрсөтө албайбыз.",
        showTranslation: "Котормосун көрсөтүү",
        hideTranslation: "Котормосун жашыруу",
        showPronunciation: "Айтылышын көрсөтүү",
        hidePronunciation: "Айтылышын жашыруу",
        showOriginal: "Түп нусканы Көрсөтүү",
        hideOriginal: "Түп нусканы Жашыруу",
        refreshLyrics: "Ырдын текстин жаңыртуу",
        showTranslationOptions: "Котормо параметрлерин көрсөтүү",
        offsetLyrics: "Сөздөрдүн жылышы",
        changeLyricsSource: "Сөз булагын өзгөртүү",
        reloadLyrics: "Сөздөрдү кайра жүктөө",
        lyricsOptions: "Сөз параметрлери",
        back: "Артка",
        reset: "Баштапкы абалга кайтаруу",
        autoSource: "Автоматтык (Демейки)",
        sourceNotFound: "Бул булактан сөздөр табылган жок"
    },
    'kk-KZ': {

        loading: "Мәтіндерді жүктеу",
        notFound: "Мәтіндер табылмады.",
        writtenBy: "Авторы: ",
        source: "Мәтіндерді ұсынған: ",
        notFoundError: "Біз мәтіндерді көрсете алмайтын сияқтымыз.",
        showTranslation: "Аудармасын көрсету",
        hideTranslation: "Аудармасын жасыру",
        showPronunciation: "Айтылуын көрсету",
        hidePronunciation: "Айтылуын жасыру",
        showOriginal: "Түпнұсқаны Көрсету",
        hideOriginal: "Түпнұсқаны Жасыру",
        refreshLyrics: "Мәтіндерді жаңарту",
        showTranslationOptions: "Аударма опцияларын көрсету",
        offsetLyrics: "Мәтін ығысуы",
        changeLyricsSource: "Мәтін көзін өзгерту",
        reloadLyrics: "Мәтінді қайта жүктеу",
        lyricsOptions: "Мәтін параметрлері",
        back: "Артқа",
        reset: "Қалпына келтіру",
        autoSource: "Автоматты (Әдепкі)",
        sourceNotFound: "Бұл дереккөзден мәтін табылмады"
    },
    'mk-MK': {

        loading: "Вчитување на текстови",
        notFound: "Не може да се најдат текстовите.",
        writtenBy: "Напишано од: ",
        source: "Текстови обезбедени од: ",
        notFoundError: "Изгледа дека не можеме да ги прикажеме текстовите.",
        showTranslation: "Прикажи превод",
        hideTranslation: "Сокриј превод",
        showPronunciation: "Прикажи изговор",
        hidePronunciation: "Сокриј изговор",
        showOriginal: "Прикажи Оригинал",
        hideOriginal: "Сокриј Оригинал",
        refreshLyrics: "Освежи текстови",
        showTranslationOptions: "Прикажи опции за превод",
        offsetLyrics: "Поместување на текстот",
        changeLyricsSource: "Промени извор на текст",
        reloadLyrics: "Превчитај текст",
        lyricsOptions: "Опции за текст",
        back: "Назад",
        reset: "Ресетирај",
        autoSource: "Автоматски (Стандардно)",
        sourceNotFound: "Не е пронајден текст од овој извор"
    },
    'mn-MN': {

        loading: "Дууны үг ачааллаж байна",
        notFound: "Дууны үг олдсонгүй.",
        writtenBy: "Бичсэн: ",
        source: "Дууны үгийг хангасан: ",
        notFoundError: "Дууны үгийг харуулах боломжгүй 것 같습니다.",
        showTranslation: "Орчуулга харуулах",
        hideTranslation: "Орчуулга нуух",
        showPronunciation: "Дуудлага харуулах",
        hidePronunciation: "Дуудлага нуух",
        showOriginal: "Эх хувийг Харуулах",
        hideOriginal: "Эх хувийг Нуух",
        refreshLyrics: "Дууны үгийг шинэчлэх",
        showTranslationOptions: "Орчуулгын сонголтуудыг харуулах",
        offsetLyrics: "Үгийн шилжилт",
        changeLyricsSource: "Үгийн эх сурвалжийг өөрчлөх",
        reloadLyrics: "Үгийг дахин ачаалах",
        lyricsOptions: "Үгийн сонголтууд",
        back: "Буцах",
        reset: "Шинэчлэх",
        autoSource: "Автомат (Үндсэн)",
        sourceNotFound: "Энэ эх сурвалжаас дууны үг олдсонгүй"
    },
    'ru-RU': {

        loading: "Загрузка текста песни",
        notFound: "Не удалось найти текст песни.",
        writtenBy: "Написано: ",
        source: "Текст песни предоставлен: ",
        notFoundError: "Похоже, мы не можем отобразить текст песни.",
        showTranslation: "Показать перевод",
        hideTranslation: "Скрыть перевод",
        showPronunciation: "Показать произношение",
        hidePronunciation: "Скрыть произношение",
        showOriginal: "Показать Оригинал",
        hideOriginal: "Скрыть Оригинал",
        refreshLyrics: "Обновить текст песни",
        showTranslationOptions: "Показать параметры перевода",
        offsetLyrics: "Смещение текста",
        changeLyricsSource: "Сменить источник текста",
        reloadLyrics: "Перезагрузить текст",
        lyricsOptions: "Параметры текста",
        back: "Назад",
        reset: "Сброс",
        autoSource: "Автоматически (По умолчанию)",
        sourceNotFound: "Текст песни из этого источника не найден"
    },
    'uk-UA': {

        loading: "Завантаження тексту",
        notFound: "Не вдалося знайти текст.",
        writtenBy: "Авторство: ",
        source: "Текст надано ",
        notFoundError: "Здається, ми не можемо показати текст.",
        showTranslation: "Показати переклад",
        hideTranslation: "Сховати переклад",
        showPronunciation: "Показати вимову",
        hidePronunciation: "Сховати вимову",
        showOriginal: "Показати оригінал",
        hideOriginal: "Сховати оригінал",
        refreshLyrics: "Перезавантажити текст",
        showTranslationOptions: "Показати параметри перекладу",
        offsetLyrics: "Зсув тексту",
        changeLyricsSource: "Змінити джерело тексту",
        reloadLyrics: "Перезавантажити текст",
        lyricsOptions: "Параметри тексту",
        back: "Назад",
        reset: "Скинути",
        autoSource: "Автоматично (За замовчуванням)",
        sourceNotFound: "Текст пісні з цього джерела не знайдено"
    },
    'el-GR': {

        loading: "Φόρτωση στίχων",
        notFound: "Δεν ήταν δυνατή η εύρεση των στίχων.",
        writtenBy: "Συνθέτης: ",
        source: "Στίχοι Παρέχονται Από: ",
        notFoundError: "Φαίνεται ότι δεν μπορούμε να εμφανίσουμε τους στίχους.",
        showTranslation: "Εμφάνιση μετάφρασης",
        hideTranslation: "Απόκρυψη μετάφρασης",
        showPronunciation: "Εμφάνιση προφοράς",
        hidePronunciation: "Απόκρυψη προφοράς",
        showOriginal: "Εμφάνιση Πρωτότυπου",
        hideOriginal: "Απόκρυψη Πρωτότυπου",
        refreshLyrics: "Ανανέωση στίχων",
        showTranslationOptions: "Εμφάνιση επιλογών μετάφρασης",
        offsetLyrics: "Μετατόπιση στίχων",
        changeLyricsSource: "Αλλαγή πηγής στίχων",
        reloadLyrics: "Επαναφόρτωση στίχων",
        lyricsOptions: "Επιλογές στίχων",
        back: "Πίσω",
        reset: "Επαναφορά",
        autoSource: "Αυτόματο (Προεπιλογή)",
        sourceNotFound: "Δεν βρέθηκαν στίχοι από αυτήν την πηγή"
    },
    'hy-AM': {

        loading: "Բեռնվում են բառերը",
        notFound: "Չհաջողվեց գտնել բառերը:",
        writtenBy: "Հեղինակ՝ ",
        source: "Բառերը տրամադրել է՝ ",
        notFoundError: "Կարծես թե չենք կարողանում ցուցադրել բառերը:",
        showTranslation: "Ցուցադրել թարգմանությունը",
        hideTranslation: "Թաքցնել թարգմանությունը",
        showPronunciation: "Ցուցադրել արտասանությունը",
        hidePronunciation: "Թաքցնել արտասանությունը",
        showOriginal: "Ցուցադրել Բնօրինակը",
        hideOriginal: "Թաքցնել Բնօրինակը",
        refreshLyrics: "Թարմացնել բառերը",
        showTranslationOptions: "Ցուցադրել թարգմանության ընտրանքները",
        offsetLyrics: "Խոսքերի շեղում",
        changeLyricsSource: "Փոխել խոսքերի աղբյուրը",
        reloadLyrics: "Վերբեռնել խոսքերը",
        lyricsOptions: "Խոսքերի ընտրանքներ",
        back: "Հետ",
        reset: "Վերականգնել",
        autoSource: "Ավտոմատ (Լռելյայն)",
        sourceNotFound: "Այս աղբյուրից խոսքեր չեն գտնվել"
    },
    'he-IL': {

        loading: "טוען מילים",
        notFound: "לא ניתן למצוא את המילים.",
        writtenBy: "נכתב על ידי: ",
        source: "מילים סופקו על ידי: ",
        notFoundError: "נראה שאנחנו לא יכולים להציג את המילים.",
        showTranslation: "הצג תרגום",
        hideTranslation: "הסתר תרגום",
        showPronunciation: "הצג הגייה",
        hidePronunciation: "הסתר הגייה",
        showOriginal: "הצג מקור",
        hideOriginal: "הסתר מקור",
        refreshLyrics: "רענן מילים",
        showTranslationOptions: "הצג אפשרויות תרגום",
        offsetLyrics: "היסט מילים",
        changeLyricsSource: "שנה מקור מילים",
        reloadLyrics: "טען מילים מחדש",
        lyricsOptions: "אפשרויות מילים",
        back: "חזרה",
        reset: "איפוס",
        autoSource: "אוטומטי (ברירת מחדל)",
        sourceNotFound: "לא נמצאו מילים ממקור זה"
    },
    'ur-PK': {

        loading: "دھن لوڈ ہو رہی ہے",
        notFound: "دھن نہیں مل سکی۔",
        writtenBy: "لکھا ہوا: ",
        source: "دھن فراہم کردہ: ",
        notFoundError: "ایسا لگتا ہے کہ ہم دھن نہیں دکھا سکتے۔",
        showTranslation: "ترجمہ دکھائیں",
        hideTranslation: "ترجمہ چھپائیں",
        showPronunciation: "تلفظ دکھائیں",
        hidePronunciation: "تلفظ چھپائیں",
        showOriginal: "اصل دکھائیں",
        hideOriginal: "اصل چھپائیں",
        refreshLyrics: "دھن تازہ کریں",
        showTranslationOptions: "ترجمہ کے اختیارات دکھائیں",
        offsetLyrics: "بول کا وقت آفسیٹ",
        changeLyricsSource: "بول کا ذریعہ تبدیل کریں",
        reloadLyrics: "بول دوبارہ لوڈ کریں",
        lyricsOptions: "بول کے اختیارات",
        back: "پیچھے",
        reset: "ری سیٹ کریں",
        autoSource: "خودکار (ڈیفالٹ)",
        sourceNotFound: "اس ذریعے سے کوئی بول نہیں ملا"
    },
    'ar-SA': {

        loading: "جارٍ تحميل كلمات الأغنية",
        notFound: "تعذر العثور على كلمات الأغنية.",
        writtenBy: "كتبه: ",
        source: "كلمات الأغنية مقدمة من: ",
        notFoundError: "يبدو أننا غير قادرين على عرض كلمات الأغنية.",
        showTranslation: "عرض الترجمة",
        hideTranslation: "إخفاء الترجمة",
        showPronunciation: "عرض النطق",
        hidePronunciation: "إخفاء النطق",
        showOriginal: "عرض الأصل",
        hideOriginal: "إخفاء الأصل",
        refreshLyrics: "تحديث كلمات الأغنية",
        showTranslationOptions: "إظهار خيارات الترجمة",
        offsetLyrics: "إزاحة كلمات الأغاني",
        changeLyricsSource: "تغيير مصدر الكلمات",
        reloadLyrics: "إعادة تحميل الكلمات",
        lyricsOptions: "خيارات الكلمات",
        back: "رجوع",
        reset: "إعادة ضبط",
        autoSource: "تلقائي (افتراضي)",
        sourceNotFound: "لم يتم العثور على كلمات من هذا المصدر"
    },
    'fa-IR': {

        loading: "در حال بارگیری متن ترانه",
        notFound: "متن ترانه پیدا نشد.",
        writtenBy: "نوشته شده توسط: ",
        source: "متن ترانه ارائه شده توسط: ",
        notFoundError: "به نظر می رسد ما قادر به نمایش متن ترانه نیستیم.",
        showTranslation: "نمایش ترجمه",
        hideTranslation: "پنهان کردن ترجمه",
        showPronunciation: "نمایش تلفظ",
        hidePronunciation: "پنهان کردن تلفظ",
        showOriginal: "نمایش اصلی",
        hideOriginal: "پنهان کردن اصلی",
        refreshLyrics: "بازخوانی متن ترانه",
        showTranslationOptions: "نمایش گزینه های ترجمه",
        offsetLyrics: "افست متن آهنگ",
        changeLyricsSource: "تغییر منبع متن آهنگ",
        reloadLyrics: "بارگیری مجدد متن آهنگ",
        lyricsOptions: "گزینه‌های متن آهنگ",
        back: "بازگشت",
        reset: "بازنشانی",
        autoSource: "خودکار (پیش‌فرض)",
        sourceNotFound: "متن آهنگی از این منبع یافت نشد"
    },
    'ne-NP': {

        loading: "गीतको बोल लोड हुँदैछ",
        notFound: "गीतको बोल फेला पार्न सकिएन।",
        writtenBy: "द्वारा लिखित: ",
        source: "गीतको बोल द्वारा प्रदान गरिएको: ",
        notFoundError: "यस्तो देखिन्छ कि हामी गीतको बोल प्रदर्शन गर्न असमर्थ छौं।",
        showTranslation: "अनुवाद देखाउनुहोस्",
        hideTranslation: "अनुवाद लुकाउनुहोस्",
        showPronunciation: "उच्चारण देखाउनुहोस्",
        hidePronunciation: "उच्चारण लुकाउनुहोस्",
        showOriginal: "मूल देखाउनुहोस्",
        hideOriginal: "मूल लुकाउनुहोस्",
        refreshLyrics: "गीतको बोल रिफ्रेस गर्नुहोस्",
        showTranslationOptions: "अनुवाद विकल्पहरू देखाउनुहोस्",
        offsetLyrics: "गीतको अफसेट",
        changeLyricsSource: "गीतको स्रोत बदल्नुहोस्",
        reloadLyrics: "गीत पुनः लोड गर्नुहोस्",
        lyricsOptions: "गीत विकल्पहरू",
        back: "पछाडि",
        reset: "रिसेट गर्नुहोस्",
        autoSource: "स्वचालित (पूर्वनिर्धारित)",
        sourceNotFound: "यस स्रोतबाट कुनै गीत फेला परेन"
    },
    'mr-IN': {

        loading: "गीत लोड होत आहे",
        notFound: "गीत सापडले नाही.",
        writtenBy: "लिहिले आहे: ",
        source: "गीत यांनी प्रदान केले: ",
        notFoundError: "असे दिसते की आम्ही गीत प्रदर्शित करू शकत नाही.",
        showTranslation: "अनुवाद दर्शवा",
        hideTranslation: "अनुवाद लपवा",
        showPronunciation: "उच्चार दर्शवा",
        hidePronunciation: "उच्चार लपवा",
        showOriginal: "मूळ दर्शवा",
        hideOriginal: "मूळ लपवा",
        refreshLyrics: "गीत रीफ्रेश करा",
        showTranslationOptions: "अनुवाद पर्याय दर्शवा",
        offsetLyrics: "गीताचा ऑफसेट",
        changeLyricsSource: "गीताचा स्रोत बदला",
        reloadLyrics: "गीत पुन्हा लोड करा",
        lyricsOptions: "गीत पर्याय",
        back: "मागे",
        reset: "रीसेट करा",
        autoSource: "स्वयंचलित (डीफॉल्ट)",
        sourceNotFound: "या स्रोताकडून कोणतेही बोल आढळले नाहीत"
    },
    'hi-IN': {

        loading: "गीत लोड हो रहा है",
        notFound: "गीत के बोल नहीं मिले।",
        writtenBy: "लेखक: ",
        source: "गीत के बोल प्रदान किए गए: ",
        notFoundError: "ऐसा लगता है कि हम गीत के बोल प्रदर्शित नहीं कर सकते।",
        showTranslation: "अनुवाद दिखाएँ",
        hideTranslation: "अनुवाद छिपाएँ",
        showPronunciation: "उच्चारण दिखाएँ",
        hidePronunciation: "उच्चारण छिपाएँ",
        showOriginal: "मूल दिखाएँ",
        hideOriginal: "मूल छिपाएँ",
        refreshLyrics: "गीत रीफ्रेश करें",
        showTranslationOptions: "अनुवाद विकल्प दिखाएँ",
        offsetLyrics: "गीत का ऑफसेट",
        changeLyricsSource: "गीत का स्रोत बदलें",
        reloadLyrics: "गीत पुनः लोड करें",
        lyricsOptions: "गीत विकल्प",
        back: "वापस",
        reset: "रीसेट",
        autoSource: "स्वचालित (डिफ़ॉल्ट)",
        sourceNotFound: "इस स्रोत से कोई गीत नहीं मिला"
    },
    'as-IN': {

        loading: "गीতৰ কথা লোড হৈ আছে",
        notFound: "गीতৰ কথা বিচাৰি পোৱা ন'গ'ল।",
        writtenBy: "द्वारा লিখিত: ",
        source: "গানের কথা দিছে: ",
        notFoundError: " এনে লাগিছে যে আমি गीतৰ কথা প্ৰদৰ্শন কৰিবলৈ অক্ষম।",
        showTranslation: "অনুবাদ দেখুৱাওক",
        hideTranslation: "অনুবাদ লুকুৱাওক",
        showPronunciation: "উচ্চাৰণ দেখুৱাওক",
        hidePronunciation: "উচ্চাৰণ লুকুৱাওк",
        showOriginal: "মূল দেখুৱাওক",
        hideOriginal: "মূল লুকুৱাওক",
        refreshLyrics: "গানের কথা সতেজ কৰক",
        showTranslationOptions: "অনুবাদ বিকল্প দেখুৱাওক",
        offsetLyrics: "গীতৰ অফচেট",
        changeLyricsSource: "গীতৰ উৎস সলনি কৰক",
        reloadLyrics: "গীত পুনৰ ল’ড কৰক",
        lyricsOptions: "গীতৰ বিকল্পসমূহ",
        back: "উভতি যাওক",
        reset: "ৰিছেট কৰক",
        autoSource: "স্বয়ংক্ৰিয় (ডিফল্ট)",
        sourceNotFound: "এই উৎসৰ পৰা কোনো গীত পোৱা নগ’ল"
    },
    'bn-IN': {

        loading: "গানের কথা লোড হচ্ছে",
        notFound: "গানের কথা খুঁজে পাওয়া যায়নি।",
        writtenBy: "লিখেছেন: ",
        source: "গানের কথা সরবরাহ করেছে: ",
        notFoundError: "মনে হচ্ছে আমরা গানের কথা প্রদর্শন করতে পারছি না।",
        showTranslation: "অনুবাদ দেখান",
        hideTranslation: "অনুবাদ লুকান",
        showPronunciation: "উচ্চারণ দেখান",
        hidePronunciation: "উচ্চারণ লুকান",
        showOriginal: "মূল দেখান",
        hideOriginal: "মূল লুকান",
        refreshLyrics: "গানের কথা রিফ্রেশ করুন",
        showTranslationOptions: "অনুবাদ বিকল্প দেখান",
        offsetLyrics: "গানের অফসেট",
        changeLyricsSource: "গানের উৎস পরিবর্তন করুন",
        reloadLyrics: "গান পুনরায় লোড করুন",
        lyricsOptions: "গানের বিকল্পসমূহ",
        back: "পেছনে",
        reset: "রিসেট",
        autoSource: "স্বয়ংক্রিয় (ডিফল্ট)",
        sourceNotFound: "এই উৎস থেকে কোনো লিরিক্স পাওয়া যায়নি"
    },
    'pa-IN': {

        loading: "ਬੋਲ ਲੋਡ ਹੋ ਰਹੇ ਹਨ",
        notFound: "ਬੋਲ ਨਹੀਂ ਮਿਲ ਸਕੇ।",
        writtenBy: "ਦੁਆਰਾ ਲਿਖਿਆ ਗਿਆ: ",
        source: "ਬੋਲ ਦੁਆਰਾ ਪ੍ਰਦਾਨ ਕੀਤੇ ਗਏ: ",
        notFoundError: "ਅਜਿਹਾ ਲਗਦਾ ਹੈ ਕਿ ਅਸੀਂ ਬੋਲ ਪ੍ਰਦਰਸ਼ਿਤ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ ਹਾਂ।",
        showTranslation: "ਅਨੁਵਾਦ ਦਿਖਾਓ",
        hideTranslation: "ਅਨੁਵਾਦ ਛੁਪਾਓ",
        showPronunciation: "ਉਚਾਰਨ ਦਿਖਾਓ",
        hidePronunciation: "ਉਚਾਰਨ ਛੁਪਾਓ",
        showOriginal: "ਮੂਲ ਦਿਖਾਓ",
        hideOriginal: "ਮੂਲ ਛੁਪਾਓ",
        refreshLyrics: "ਬੋਲ ਤਾਜ਼ਾ ਕਰੋ",
        showTranslationOptions: "ਅਨੁਵਾਦ ਵਿਕਲਪ ਦਿਖਾਓ",
        offsetLyrics: "ਬੋਲਾਂ ਦਾ ਆਫਸੈੱਟ",
        changeLyricsSource: "ਬੋਲਾਂ ਦਾ ਸਰੋਤ ਬਦਲੋ",
        reloadLyrics: "ਬੋਲ ਦੁਬਾਰਾ ਲੋਡ ਕਰੋ",
        lyricsOptions: "ਬੋਲਾਂ ਦੇ ਵਿਕਲਪ",
        back: "ਪਿੱਛੇ",
        reset: "ਰੀਸੈੱਟ",
        autoSource: "ਆਟੋਮੈਟਿਕ (ਡਿਫਾਲਟ)",
        sourceNotFound: "ਇਸ ਸਰੋਤ ਤੋਂ ਕੋਈ ਬੋਲ ਨਹੀਂ ਮਿਲੇ"
    },
    'gu-IN': {

        loading: "ગીતના બોલ લોડ થઈ રહ્યા છે",
        notFound: "ગીતના બોલ શોધી શકાયા નથી.",
        writtenBy: "દ્વારા લખાયેલ: ",
        source: "ગીતના બોલ દ્વારા પ્રદાન કરેલ: ",
        notFoundError: "એવું લાગે છે કે અમે ગીતના બોલ પ્રદર્શિત કરવામાં અસમર્થ છીએ.",
        showTranslation: "અનુવાદ બતાવો",
        hideTranslation: "અનુવાદ છુપાવો",
        showPronunciation: "ઉચ્ચાર બતાવો",
        hidePronunciation: "ઉચ્ચાર છુપાવો",
        showOriginal: "મૂળ બતાવો",
        hideOriginal: "મૂળ છુપાવો",
        refreshLyrics: "ગીતના બોલ તાજા કરો",
        showTranslationOptions: "અનુવાદ વિકલ્પો બતાવો",
        offsetLyrics: "ગીતના શબ્દોનો ઑફસેટ",
        changeLyricsSource: "ગીતના શબ્દોનો સ્ત્રોત બદલો",
        reloadLyrics: "ગીત ફરીથી લોડ કરો",
        lyricsOptions: "ગીતના વિકલ્પો",
        back: "પાછા",
        reset: "રીસેટ",
        autoSource: "સ્વચાલિત (ડિફૉલ્ટ)",
        sourceNotFound: "આ સ્ત્રોતમાંથી કોઈ ગીતના શબ્દો મળ્યા નથી"
    },
    'or-IN': {

        loading: "ଗୀତର ବୋଲ ଲୋଡ୍ କରୁଛି",
        notFound: "ଗୀତର ବୋଲ ମିଳିଲା ନାହିଁ |",
        writtenBy: "ଏହା ଦ୍ୱାରା ଲିଖିତ: ",
        source: "ଗୀତର ବୋଲ ଏହା ଦ୍ୱାରା ପ୍ରଦାନ କରାଯାଇଛି: ",
        notFoundError: "ଏହା ଜଣାପଡୁଛି ଯେ ଆମେ ଗୀତର ବୋଲ ପ୍ରଦର୍ଶନ କରିବାରେ ଅସମର୍ଥ |",
        showTranslation: "ଅନୁବାଦ ଦେଖାନ୍ତୁ",
        hideTranslation: "ଅନୁବାଦ ଲୁଚାନ୍ତୁ",
        showPronunciation: "ଉଚ୍ଚାରଣ ଦେଖାନ୍ତୁ",
        hidePronunciation: "ଉଚ୍ଚାରଣ ଲୁଚାନ୍ତୁ",
        showOriginal: "ମୂଳ ଦେଖାନ୍ତୁ",
        hideOriginal: "ମୂଳ ଲୁଚାନ୍ତୁ",
        refreshLyrics: "ଗୀତର ବୋଲ ରିଫ୍ରେସ୍ କରନ୍ତୁ",
        showTranslationOptions: "ଅନୁବାଦ ବିକଳ୍ପ ଦେଖାନ୍ତୁ",
        offsetLyrics: "ଗୀତ ଅଫସେଟ୍",
        changeLyricsSource: "ଗୀତର ଉତ୍ସ ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
        reloadLyrics: "ଗୀତ ପୁନଃ ଲୋଡ୍ କରନ୍ତୁ",
        lyricsOptions: "ଗୀତ ବିକଳ୍ପ",
        back: "ପଛକୁ",
        reset: "ରିସେଟ୍",
        autoSource: "ସ୍ୱୟଂଚାଳିତ (ଡିଫଲ୍ଟ)",
        sourceNotFound: "ଏହି ଉତ୍ସରୁ କୌଣସି ଗୀତ ମିଳିଲା ନାହିଁ"
    },
    'ta-IN': {

        loading: "பாடல் வரிகள் ஏற்றಲಾಗುತ್ತಿದೆ",
        notFound: "பாடல் வரிகளைக் கண்டுபிடிக்க முடியவில்லை.",
        writtenBy: "எழுதியவர்: ",
        source: "பாடல் வரிகள் வழங்கியவர்: ",
        notFoundError: "பாடல் வரிகளைக் காட்ட முடியவில்லை என்று தெரிகிறது.",
        showTranslation: "மொழிபெயர்ப்பைக் காட்டு",
        hideTranslation: "மொழிபெயர்ப்பை மறை",
        showPronunciation: "உச்சரிப்பைக் காட்டு",
        hidePronunciation: "உச்சரிப்பை மறை",
        showOriginal: "அசல் காட்டு",
        hideOriginal: "அசல் மறை",
        refreshLyrics: "பாடல் வரிகளைப் புதுப்பி",
        showTranslationOptions: "மொழிபெயர்ப்பு விருப்பங்களைக் காட்டு",
        offsetLyrics: "வரிகள் ஆஃப்செட்",
        changeLyricsSource: "வரிகள் மூலத்தை மாற்றவும்",
        reloadLyrics: "வரிகளை மீண்டும் ஏற்றவும்",
        lyricsOptions: "வரிகள் விருப்பங்கள்",
        back: "பின்செல்",
        reset: "மீட்டமை",
        autoSource: "தானியங்கி (இயல்புநிலை)",
        sourceNotFound: "இந்த மூலத்திலிருந்து வரிகள் எதுவும் கிடைக்கவில்லை"
    },
    'te-IN': {

        loading: "సాహిత్యం లోడ్ అవుతోంది",
        notFound: "సాహిత్యాన్ని కనుగొనలేకపోయింది.",
        writtenBy: "రాసినవారు: ",
        source: "సాహిత్యం అందించినవారు: ",
        notFoundError: "మేము సాహిత్యాన్ని ప్రదర్శించలేమని తెలుస్తోంది.",
        showTranslation: "అనువాదాన్ని చూపించు",
        hideTranslation: "అనువాదాన్ని దాచు",
        showPronunciation: "ఉచ్చారణను చూపించు",
        hidePronunciation: "ఉచ్చారణను దాచు",
        showOriginal: "అసలు చూపించు",
        hideOriginal: "అసలు దాచు",
        refreshLyrics: "సాహిత్యాన్ని రిఫ్రెష్ చేయండి",
        showTranslationOptions: "అనువాద ఎంపికలను చూపించు",
        offsetLyrics: "సాహిత్యం ఆఫ్‌సెట్",
        changeLyricsSource: "సాహిత్యం మూలాన్ని మార్చండి",
        reloadLyrics: "సాహిత్యాన్ని మళ్లీ లోడ్ చేయండి",
        lyricsOptions: "సాహిత్యం ఎంపికలు",
        back: "వెనుకకు",
        reset: "రీసెట్",
        autoSource: "స్వయంచాలక (డిఫాల్ట్)",
        sourceNotFound: "ఈ మూలం నుండి సాహిత్యం కనుగొనబడలేదు"
    },
    'kn-IN': {

        loading: "ಸಾಹಿತ್ಯವನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ",
        notFound: "ಸಾಹಿತ್ಯವನ್ನು ಹುಡುಕಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
        writtenBy: "ಬರೆದವರು: ",
        source: "ಸಾಹಿತ್ಯವನ್ನು ಒದಗಿಸಿದವರು: ",
        notFoundError: "ನಾವು ಸಾಹಿತ್ಯವನ್ನು ಪ್ರದರ್ಶಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ ಎಂದು ತೋರುತ್ತದೆ.",
        showTranslation: "ಅನುವಾದವನ್ನು ತೋರಿಸಿ",
        hideTranslation: "ಅನುವಾದವನ್ನು ಮರೆಮಾಡಿ",
        showPronunciation: "ಉಚ್ಚಾರಣೆಯನ್ನು ತೋರಿಸಿ",
        hidePronunciation: "ಉಚ್ಚಾರಣೆಯನ್ನು ಮರೆಮಾಡಿ",
        showOriginal: "ಮೂಲವನ್ನು ತೋರಿಸಿ",
        hideOriginal: "ಮೂಲವನ್ನು ಮರೆಮಾಡಿ",
        refreshLyrics: "ಸಾಹಿತ್ಯವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ",
        showTranslationOptions: "ಅನುವಾದ ಆಯ್ಕೆಗಳನ್ನು ತೋರಿಸಿ",
        offsetLyrics: "ಸಾಹಿತ್ಯದ ಆಫ್‌ಸೆಟ್",
        changeLyricsSource: "ಸಾಹಿತ್ಯದ ಮೂಲವನ್ನು ಬದಲಾಯಿಸಿ",
        reloadLyrics: "ಸಾಹಿತ್ಯವನ್ನು ಮರುಲೋಡ್ ಮಾಡಿ",
        lyricsOptions: "ಸಾಹಿತ್ಯದ ಆಯ್ಕೆಗಳು",
        back: "ಹಿಂದೆ",
        reset: "ಮರುಹೊಂದಿಸಿ",
        autoSource: "ಸ್ವಯಂಚಾಲಿತ (ಡೀಫಾಲ್ಟ್)",
        sourceNotFound: "ಈ ಮೂಲದಿಂದ ಯಾವುದೇ ಸಾಹಿತ್ಯ ಕಂಡುಬಂದಿಲ್ಲ"
    },
    'ml-IN': {

        loading: "വരികൾ ലോഡുചെയ്യുന്നു",
        notFound: "വരികൾ കണ്ടെത്താനായില്ല.",
        writtenBy: "എഴുതിയത്: ",
        source: "വരികൾ നൽകിയത്: ",
        notFoundError: "വരികൾ പ്രദർശിപ്പിക്കാൻ ഞങ്ങൾക്ക് കഴിയില്ലെന്ന് തോന്നുന്നു.",
        showTranslation: "പരിഭാഷ കാണിക്കുക",
        hideTranslation: "പരിഭാഷ മറയ്ക്കുക",
        showPronunciation: "ഉച്ചാരണം കാണിക്കുക",
        hidePronunciation: "ഉച്ചാരണം മറയ്ക്കുക",
        showOriginal: "യഥാർത്ഥ കാണിക്കുക",
        hideOriginal: "യഥാർത്ഥ മറയ്ക്കുക",
        refreshLyrics: "വരികൾ പുതുക്കുക",
        showTranslationOptions: "വിവർത്തന ഓപ്ഷനുകൾ കാണിക്കുക",
        offsetLyrics: "വരികളുടെ ഓഫ്‌സെറ്റ്",
        changeLyricsSource: "വരികളുടെ ഉറവിടം മാറ്റുക",
        reloadLyrics: "വരികൾ വീണ്ടും ലോഡുചെയ്യുക",
        lyricsOptions: "വരികളുടെ ഓപ്ഷനുകൾ",
        back: "പിന്നിലേക്ക്",
        reset: "റീസെറ്റ് ചെയ്യുക",
        autoSource: "യാന്ത്രികം (സ്ഥിരസ്ഥിതി)",
        sourceNotFound: "ഈ ഉറവിടത്തിൽ നിന്ന് വരികളൊന്നും കണ്ടെത്തിയില്ല"
    },
    'si-LK': {

        loading: "පද රචනය පූරණය වෙමින් පවතී",
        notFound: "පද රචනය සොයාගත නොහැකි විය.",
        writtenBy: "ලියන ලද්දේ: ",
        source: "පද රචනය සපයන ලද්දේ: ",
        notFoundError: "අපට පද රචනය ප්‍රදර්ශනය කළ නොහැකි බව පෙනේ.",
        showTranslation: "පරිවර්තනය පෙන්වන්න",
        hideTranslation: "පරිවර්තනය සඟවන්න",
        showPronunciation: "උච්චාරණය පෙන්වන්න",
        hidePronunciation: "උච්චාරණය සඟවන්න",
        showOriginal: "මුල් පිටපත පෙන්වන්න",
        hideOriginal: "මුල් පිටපත සඟවන්න",
        refreshLyrics: "පද රචනය නැවත පූരණය කරන්න",
        showTranslationOptions: "පරිවර්තන විකල්ප පෙන්වන්න",
        offsetLyrics: "පද පේළි ඕෆ්සෙට්",
        changeLyricsSource: "පද මූලාශ්‍රය වෙනස් කරන්න",
        reloadLyrics: "පද නැවත පූරණය කරන්න",
        lyricsOptions: "පද විකල්ප",
        back: "ආපසු",
        reset: "යළි පිහිටුවන්න",
        autoSource: "ස්වයංක්‍රීය (පෙරනිමි)",
        sourceNotFound: "මෙම මූලාශ්‍රයෙන් පද හමු නොවීය"
    },
    'th-TH': {

        loading: "กำลังโหลดเนื้อเพลง",
        notFound: "ไม่พบเนื้อเพลง",
        writtenBy: "ประพันธ์โดย: ",
        source: "เนื้อเพลงโดย: ",
        notFoundError: "ดูเหมือนว่าเราจะไม่สามารถแสดงเนื้อเพลงได้",
        showTranslation: "แสดงคำแปล",
        hideTranslation: "ซ่อนคำแปล",
        showPronunciation: "แสดงการออกเสียง",
        hidePronunciation: "ซ่อนการออกเสียง",
        showOriginal: "แสดงต้นฉบับ",
        hideOriginal: "ซ่อนต้นฉบับ",
        refreshLyrics: "รีเฟรชเนื้อเพลง",
        showTranslationOptions: "แสดงตัวเลือกการแปล",
        offsetLyrics: "การปรับหน่วงเวลาเนื้อเพลง",
        changeLyricsSource: "เปลี่ยนแหล่งที่มาของเนื้อเพลง",
        reloadLyrics: "โหลดเนื้อเพลงใหม่",
        lyricsOptions: "ตัวเลือกเนื้อเพลง",
        back: "ย้อนกลับ",
        reset: "รีเซ็ต",
        autoSource: "อัตโนมัติ (ค่าเริ่มต้น)",
        sourceNotFound: "ไม่พบเนื้อเพลงจากแหล่งนี้"
    },
    'lo-LA': {

        loading: "ກຳລັງໂຫລດເນື້ອເພງ",
        notFound: "ບໍ່ສາມາດຊອກຫາເນື້ອເພງໄດ້.",
        writtenBy: "ຂຽນໂດຍ: ",
        source: "ເນື້ອເພງສະໜອງໃຫ້ໂດຍ: ",
        notFoundError: "ເບິ່ງຄືວ່າພວກເຮົາບໍ່ສາມາດສະແດງເນື້ອເພງໄດ້.",
        showTranslation: "ສະແດງການແປ",
        hideTranslation: "ເຊື່ອງການແປ",
        showPronunciation: "ສະແດງການອອກສຽງ",
        hidePronunciation: "ເຊື່ອງການອອກສຽງ",
        showOriginal: "ສະແດງຕົ້ນສະບັບ",
        hideOriginal: "ເຊື່ອງຕົ້ນສະບັບ",
        refreshLyrics: "ໂຫຼດເນື້ອເພງຄືນໃໝ່",
        showTranslationOptions: "ສະແດງຕົວເລືອກການແປ",
        offsetLyrics: "ໄລຍະເລື່ອນເນື້ອເພງ",
        changeLyricsSource: "ປ່ຽນແຫຼ່ງເນື້ອເພງ",
        reloadLyrics: "ໂຫລດເນື້ອເພງຄືນໃໝ່",
        lyricsOptions: "ຕົວເລືອກເນື້ອເພງ",
        back: "ກັບຄືນ",
        reset: "ຣີເຊັດ",
        autoSource: "ອັດຕະໂນມັດ (ຄ່າເລີ່ມຕົ້ນ)",
        sourceNotFound: "ບໍ່ພົບເນື້ອເພງຈາກແຫຼ່ງນີ້"
    },
    'my-MM': {

        loading: "စာသားများအား တင်နေသည်",
        notFound: "စာသားများ ရှာမတွေ့ပါ။",
        writtenBy: "ရေးသားသူ: ",
        source: "စာသားများအား ပံ့ပိုးပေးသည်- ",
        notFoundError: "ကျွန်ုပ်တို့ စာသားများအား ပြသနိုင်ခြင်း မရှိပုံပေါ်ပါသည်။",
        showTranslation: "ဘာသာပြန်ချက်ကို ပြပါ",
        hideTranslation: "ဘာသာပြန်ချက်ကို ဖျောက်ပါ",
        showPronunciation: "အသံထွက်ကို ပြပါ",
        hidePronunciation: "အသံထွက်ကို ဖျောက်ပါ",
        showOriginal: "မူရင်းကို ပြပါ",
        hideOriginal: "မူရင်းကို ဖျောက်ပါ",
        refreshLyrics: "စာသားများအား ပြန်လည်စတင်ပါ",
        showTranslationOptions: "ဘာသာပြန်ရွေးချယ်စရာများကို ပြပါ",
        offsetLyrics: "စာသား အချိန်ညှိမှု",
        changeLyricsSource: "စာသား ရင်းမြစ် ပြောင်းရန်",
        reloadLyrics: "စာသား ပြန်လည်ဖွင့်ရန်",
        lyricsOptions: "စာသား ရွေးချယ်စရာများ",
        back: "နောက်သို့",
        reset: "ပြန်လည်သတ်မှတ်ရန်",
        autoSource: "အလိုအလျောက် (မူရင်း)",
        sourceNotFound: "ဤရင်းမြစ်မှ စာသား မတွေ့ရှိပါ"
    },
    'ka-GE': {

        loading: "იტვირთება ტექსტები",
        notFound: "ტექსტები ვერ მოიძებნა.",
        writtenBy: "ავტორი: ",
        source: "ტექსტები მოწოდებულია: ",
        notFoundError: "როგორც ჩანს, ტექსტებს ვერ ვაჩვენებთ.",
        showTranslation: "თარგმანის ჩვენება",
        hideTranslation: "თარგმანის დამალვა",
        showPronunciation: "წარმოთქმის ჩვენება",
        hidePronunciation: "წარმოთქმის დამალვა",
        showOriginal: "ორიგინალის ჩვენება",
        hideOriginal: "ორიგინალის დამალვა",
        refreshLyrics: "ტექსტების განახლება",
        showTranslationOptions: "თარგმანის პარამეტრების ჩვენება",
        offsetLyrics: "ტექსტის წანაცვლება",
        changeLyricsSource: "ტექსტის წყაროს შეცვლა",
        reloadLyrics: "ტექსტის ხელახლა ჩატვირთვა",
        lyricsOptions: "ტექსტის პარამეტრები",
        back: "უკან",
        reset: "ჩამოყრა",
        autoSource: "ავტომატური (ნაგულისხმევი)",
        sourceNotFound: "ამ წყაროდან ტექსტი ვერ მოიძებნა"
    },
    'am-ET': {

        loading: "ግጥሞችን በመጫን ላይ",
        notFound: "ግጥሞቹን ማግኘት አልተቻለም።",
        writtenBy: "የተፃፈው በ: ",
        source: "ግጥሞች የቀረቡት በ: ",
        notFoundError: "ግጥሞቹን ማሳየት ያልቻልን ይመስላል።",
        showTranslation: "ትርጉም አሳይ",
        hideTranslation: "ትርጉም ደብቅ",
        showPronunciation: "አነባበብ አሳይ",
        hidePronunciation: "አነባበብ ደብቅ",
        showOriginal: "ዋናውን አሳይ",
        hideOriginal: "ዋናውን ደብቅ",
        refreshLyrics: "ግጥሞችን አድስ",
        showTranslationOptions: "የትርጉም አማራጮችን አሳይ",
        offsetLyrics: "የግጥም ማካካሻ",
        changeLyricsSource: "የግጥም ምንጭ ቀይር",
        reloadLyrics: "ግጥሙን እንደገና ጫን",
        lyricsOptions: "የግጥም አማራጮች",
        back: "ተመለስ",
        reset: "ዳግም አስጀምር",
        autoSource: "አውቶማቲክ (ነባሪ)",
        sourceNotFound: "ከዚህ ምንጭ ምንም ግጥሞች አልተገኙም"
    },
    'km-KH': {

        loading: "កំពុង​ផ្ទុក​អត្ថបទ​ចម្រៀង",
        notFound: "​មិន​អាច​រក​ឃើញ​អត្ថបទ​ចម្រៀង​ទេ។",
        writtenBy: "និពន្ធ​โดย: ",
        source: "អត្ថបទ​ចម្រៀង​ផ្ដល់​ให้​โดย: ",
        notFoundError: "ហាក់​ដូច​ជា​យើង​មិន​អាច​បង្ហាញ​អត្ថបទ​ចម្រៀង​បាន​ទេ។",
        showTranslation: "បង្ហាញ​ការ​បកប្រែ",
        hideTranslation: "លាក់​ការ​បកប្រែ",
        showPronunciation: "បង្ហាញ​ការ​បញ្ចេញ​សំឡេង",
        hidePronunciation: "លាក់​ការ​បញ្ចេញ​សំឡេង",
        showOriginal: "បង្ហាញ​ដើម",
        hideOriginal: "លាក់​ដើម",
        refreshLyrics: "ផ្ទុក​អត្ថបទ​ចម្រៀង​ឡើងវិញ",
        showTranslationOptions: "បង្ហាញ​ជម្រើស​បកប្រែ",
        offsetLyrics: "គម្លាតទំនុកច្រៀង",
        changeLyricsSource: "ផ្លាស់ប្តូរប្រភពទំនុកច្រៀង",
        reloadLyrics: "ផ្ទុកទំនុកច្រៀងឡើងវិញ",
        lyricsOptions: "ជម្រើសទំនុកច្រៀង",
        back: "ថយក្រោយ",
        reset: "កំណត់ឡើងវិញ",
        autoSource: "ស្វ័យប្រវត្តិ (លំនាំដើម)",
        sourceNotFound: "រកមិនឃើញទំនុកច្រៀងពីប្រភពនេះទេ"
    },
    'zh-CN': {

        loading: "加载歌词",
        notFound: "无法找到歌词。",
        writtenBy: "作者: ",
        source: "歌词提供方: ",
        notFoundError: "看起来我们无法显示歌词。",
        showTranslation: "显示翻译",
        hideTranslation: "隐藏翻译",
        showPronunciation: "显示发音",
        hidePronunciation: "隐藏发音",
        showOriginal: "显示原文",
        hideOriginal: "隐藏原文",
        refreshLyrics: "刷新歌词",
        showTranslationOptions: "显示翻译选项",
        offsetLyrics: "歌词延迟调整",
        changeLyricsSource: "更改歌词源",
        reloadLyrics: "重新加载歌词",
        lyricsOptions: "歌词选项",
        back: "返回",
        reset: "重置",
        autoSource: "自动（默认）",
        sourceNotFound: "未从该源找到歌词"
    },
    'zh-TW': {

        loading: "載入歌詞",
        notFound: "找不到歌詞。",
        writtenBy: "作者：",
        source: "歌詞提供：",
        notFoundError: "我們似乎無法顯示歌詞。",
        showTranslation: "顯示翻譯",
        hideTranslation: "隱藏翻譯",
        showPronunciation: "顯示發音",
        hidePronunciation: "隱藏發音",
        showOriginal: "顯示原文",
        hideOriginal: "隱藏原文",
        refreshLyrics: "重新整理歌詞",
        showTranslationOptions: "顯示翻譯選項",
        offsetLyrics: "歌詞延遲調整",
        changeLyricsSource: "變更歌詞來源",
        reloadLyrics: "重新載入歌詞",
        lyricsOptions: "歌詞選項",
        back: "返回",
        reset: "重設",
        autoSource: "自動（預設）",
        sourceNotFound: "未從此來源找到歌詞"
    },
    'zh-HK': {

        loading: "載入歌詞",
        notFound: "找不到歌詞。",
        writtenBy: "作者：",
        source: "歌詞提供：",
        notFoundError: "我們似乎無法顯示歌詞。",
        showTranslation: "顯示翻譯",
        hideTranslation: "隱藏翻譯",
        showPronunciation: "顯示發音",
        hidePronunciation: "隱藏發音",
        showOriginal: "顯示原文",
        hideOriginal: "隱藏原文",
        refreshLyrics: "重新整理歌詞",
        showTranslationOptions: "顯示翻譯選項",
        offsetLyrics: "歌詞延遲調整",
        changeLyricsSource: "變更歌詞來源",
        reloadLyrics: "重新載入歌詞",
        lyricsOptions: "歌詞選項",
        back: "返回",
        reset: "重設",
        autoSource: "自動（預設）",
        sourceNotFound: "未從此來源找到歌詞"
    },
    'ja-JP': {

        loading: "歌詞を読み込んでいます",
        notFound: "歌詞が見つかりませんでした。",
        writtenBy: "作詞: ",
        source: "歌詞提供: ",
        notFoundError: "歌詞を表示できないようです。",
        showTranslation: "翻訳を表示",
        hideTranslation: "翻訳を非表示",
        showPronunciation: "発音を表示",
        hidePronunciation: "発音を非表示",
        showOriginal: "オリジナルを表示",
        hideOriginal: "オリジナルを非表示",
        refreshLyrics: "歌詞を更新",
        showTranslationOptions: "翻訳オプションを表示",
        offsetLyrics: "歌詞のオフセット",
        changeLyricsSource: "歌詞のソースを変更",
        reloadLyrics: "歌詞を再読み込み",
        lyricsOptions: "歌詞のオプション",
        back: "戻る",
        reset: "リセット",
        autoSource: "自動（デフォルト）",
        sourceNotFound: "このソースから歌詞が見つかりませんでした"
    },
    'ko-KR': {

        loading: "가사 불러오는 중",
        notFound: "가사를 찾을 수 없습니다.",
        writtenBy: "작사: ",
        source: "가사 제공: ",
        notFoundError: "가사를 표시할 수 없는 것 같습니다.",
        showTranslation: "번역 보기",
        hideTranslation: "번역 숨기기",
        showPronunciation: "발음 보기",
        hidePronunciation: "발음 숨기기",
        showOriginal: "원본 보기",
        hideOriginal: "원본 숨기기",
        refreshLyrics: "가사 새로고침",
        showTranslationOptions: "번역 옵션 표시",
        offsetLyrics: "가사 오프셋",
        changeLyricsSource: "가사 출처 변경",
        reloadLyrics: "가사 다시 로드",
        lyricsOptions: "가사 옵션",
        back: "뒤로",
        reset: "재설정",
        autoSource: "자동 (기본값)",
        sourceNotFound: "이 출처에서 가사를 찾을 수 없습니다"
    }
};

function getUserLanguage() {
    // Get the browser's language, default to 'en-US' if not available.
    const userLang = document.documentElement.lang || 'en-US';

    if (userLang in translations) {
        return userLang;
    }
    const baseLang = userLang.split('-')[0];

    if (baseLang in translations) {
        return baseLang;
    }

    for (const key in translations) {
        if (key.startsWith(baseLang + '-')) {
            return key; // Return the first matching dialect we find.
        }
    }

    //If no match could be found at all, return the ultimate default.
    return 'en-US';
}

function t(key) {
    const lang = getUserLanguage();
    return translations[lang]?.[key] || translations['en-US'][key];
}